export const siteConfig = {
  showName: "The Superlative Podcast",
  tagline: "One conversation. One guest. No ceiling.",
  host: "Edward Buchi",
  hostHandle: "@thespeakerlisan",

  // Links — update these before launch
  xProfileUrl: "https://x.com/thespeakerlisan",
  youtubeUrl: "https://www.youtube.com/@TheSuperlativePodcast",
  calendlyUrl: "https://cal.com/smsp-schedhuler/pdon30", // Guest booking link

  // Episode feed config — switch source without rebuilding
  episodeFeed: {
    // "x" | "youtube"
    source: "x" as "x" | "youtube",
    // X timeline embed handle (without @)
    xHandle: "thespeakerlisan",
    // YouTube playlist embed ID (for future use)
    youtubePlaylistId: "",
  },

  // Featured episodes — add new episodes at the top
  // xUrl: X broadcast or post link | youtubeUrl: YouTube video or livestream link
  episodes: [
    {
      title: "Episode 29",
      episodeTitle: "Faith Is a Due Diligence Filter",
      guest: "Sebastian Harris",
      guestTitle: "Founder & Managing Partner",
      guestCompany: "Sandbox Fund",
      youtubeUrl: "https://www.youtube.com/live/4HFr7VQ_zwk",
    },
    {
      title: "Episode 28",
      episodeTitle: "Compute Is About to Get Absurdly Cheap & Efficient",
      guest: "Craig Taggart",
      guestTitle: "Venture Partner",
      guestCompany: "Qubits Ventures",
      youtubeUrl: "https://www.youtube.com/live/meHYE_KWF0Q",
    },
    {
      title: "Episode 27",
      episodeTitle: "Everyone Is Chasing Longevity. She Says They're Wrong.",
      guest: "Mansi Aggarwal",
      guestTitle: "Founding Partner",
      guestCompany: "Alkemi Growth Capital",
      youtubeUrl: "https://www.youtube.com/live/lYYbDRyb9_M",
    },
    {
      title: "Episode 26",
      episodeTitle: "The AI Layer Deciding Your Brand's Fate",
      guest: "Caleb Pedosiuk",
      guestTitle: "Creative Director & CEO",
      guestCompany: "79 Development",
      youtubeUrl: "https://www.youtube.com/live/hbptJH2NEI8",
    },
    {
      title: "Episode 25",
      episodeTitle: "Genetics Is the Breakthrough Nobody's Ready For",
      guest: "Jonah Probell",
      guestTitle: "Managing Partner",
      guestCompany: "Lexi Ventures",
      youtubeUrl: "https://www.youtube.com/live/8BnbvEi48Ns",
    },
    {
      title: "Episode 24",
      episodeTitle: "He Stopped Pitching and Started Broadcasting",
      guest: "Rudi Adigbli",
      guestTitle: "Founder",
      guestCompany: "ReeWire Ventures",
      youtubeUrl: "https://www.youtube.com/live/MmBqf22JEcM",
    },
    {
      title: "Episode 23",
      episodeTitle: "AI Killed the Startups It Was Supposed to Help",
      guest: "Susana Espinosa de los Reyes",
      guestTitle: "Partner",
      guestCompany: "Dux Capital",
      youtubeUrl: "https://www.youtube.com/live/NfNbhh_bM5E?si=z_cFtUmJY7-4IG5T",
    },
    {
      title: "Episode 22",
      episodeTitle: "The World's Biggest Asset Has No Tech Yet",
      guest: "Carlos Rousseau",
      guestTitle: "Managing Partner",
      guestCompany: "Second Century Ventures",
      youtubeUrl: "https://www.youtube.com/live/kQtoGvSX8X8?si=4k2pVOWsFSh6CfSX",
    },
    {
      title: "Episode 21",
      episodeTitle: "YouTube Can't Fix a Gas Leak",
      guest: "Julian Scadden",
      guestTitle: "President & CEO",
      guestCompany: "Nexstar Network",
      youtubeUrl: "https://www.youtube.com/live/2mob1KF3PD0?si=MzaFFW0_GNVQrPIA",
    },
    {
      title: "Episode 20",
      episodeTitle: "The Last 5% Breaks Everything, an Introspective of the Drone Industry",
      guest: "Vadim Tarasov",
      guestTitle: "Managing Partner",
      guestCompany: "AAS Fund & UAVOS",
      youtubeUrl: "https://www.youtube.com/live/hd5SVjxTE34?si=slELN3M5m7ZNDnva",
    },
    {
      title: "Episode 19",
      episodeTitle: "The Tetrad, Machine and What the Medium Is Doing to Us Now",
      guest: "Andrew McLuhan",
      guestTitle: "Founder",
      guestCompany: "The McLuhan Institute",
      youtubeUrl: "https://www.youtube.com/live/dQVk8XGIyxs?si=khF2EeUKoPGuYlOo",
    },
    {
      title: "Episode 18",
      episodeTitle: "The Comma Is Where the Story Turns",
      guest: "Ashley Heron",
      guestTitle: "Founder",
      guestCompany: "Comma8",
      youtubeUrl: "https://youtube.com/live/accgqB3TOc0",
    },
    {
      title: "Episode 17",
      episodeTitle: "The Capital Formation Game Has Changed – Most VCs Still Don't Get It",
      guest: "Andrew Romans",
      guestTitle: "Managing Partner",
      guestCompany: "7BC Venture Capital",
      youtubeUrl: "https://youtube.com/live/aJ4cIgAtvGU",
    },
    {
      title: "Episode 16",
      episodeTitle: "It's Usually Not Money. It's Connections and Broken Barriers.",
      guest: "Daniela Pacheco",
      guestTitle: "Partner",
      guestCompany: "NVGroup",
      youtubeUrl: "https://youtube.com/live/lNAsH1evEcU",
    },
    {
      title: "Episode 15",
      episodeTitle: "AI Is Being Locked Down Like the Atomic Bomb, the Hidden Danger of This Policy",
      guest: "Lindley Lentati",
      guestTitle: "Founder",
      guestCompany: "Cambridge Inference",
      youtubeUrl: "https://youtube.com/live/0mRzdim0T4I",
    },
    {
      title: "Episode 14",
      episodeTitle: "You Don't Get to Decide What Your Brand Is",
      guest: "Justin Oberman",
      guestTitle: "Founder",
      guestCompany: "Oberman Partners",
      xUrl: "https://x.com/i/broadcasts/1lJQRvyVPNMxE",
      youtubeUrl: "https://www.youtube.com/live/VXm3utlnql4?si=6VwPBb_8X9EyTP8s",
    },
    {
      title: "Episode 13",
      episodeTitle: "Coastal VCs Haven't Looked Here. That's the Entire Thesis.",
      guest: "Jay Yarlagadda",
      guestTitle: "General Partner",
      guestCompany: "Atoms VC",
      xUrl: "https://x.com/i/broadcasts/1dGYljOWZXlKX",
      youtubeUrl: "https://www.youtube.com/live/rWPPVG51iDQ?si=TcFKYu9_4RRxBXvb",
    },
    {
      title: "Episode 12",
      episodeTitle: "After Watching Businesses Fail, She Ended Up Operating a VC Fund",
      guest: "Emily Kegels",
      guestTitle: "Partner",
      guestCompany: "PitchDrive VC",
      xUrl: "https://x.com/thespeakerlisan/status/2051294075001975085",
      youtubeUrl: "https://www.youtube.com/live/zeJbxqsBUcs?si=KcdDRcvd6Ya7iJRm",
    },
    {
      title: "Episode 11",
      episodeTitle: "The VC Model Was Designed to Make 95% of Founders Fail",
      guest: "Justin Reynolds",
      guestTitle: "Founder & Venture Builder",
      guestCompany: "Tashinga Partnership",
      xUrl: "https://x.com/i/broadcasts/1AKEmOVqgvnKL",
      youtubeUrl: "https://www.youtube.com/watch?v=KrfY5Kjbd44",
    },
    {
      title: "Episode 10",
      episodeTitle: "He Turned Down a Google Acquisition. The Company Outperformed the Exit.",
      guest: "Peter Micca",
      guestTitle: "Managing Partner",
      guestCompany: "Caduceus Capital Partners",
      youtubeUrl: "https://youtu.be/VYSBwQBJfXM?si=pjbGntcYwtkam1pL",
    },
    {
      title: "Episode 9",
      episodeTitle: "He Convinced a DeFi Protocol to Lend to Small Businesses",
      guest: "Mark Francis",
      guestTitle: "Founder",
      guestCompany: "Preferred",
      xUrl: "https://x.com/i/broadcasts/1PKqrEZDVgQGb",
      youtubeUrl: "https://www.youtube.com/watch?v=UpphOFgNhh4",
    },
    {
      title: "Episode 8",
      episodeTitle: "He Left a $20B Hedge Fund to Back the Infrastructure Everyone Else Ignored",
      guest: "Matt Ober",
      guestTitle: "Managing Partner",
      guestCompany: "Social Leverage",
      xUrl: "https://x.com/i/broadcasts/1nJOLEdOQEkxR",
    },
    {
      title: "Episode 7",
      episodeTitle: "Bought Bitcoin at $1. Nobody Listened.",
      guest: "DaVinci Jeremie",
      guestTitle: "Bitcoin Pioneer & Crypto Educator",
      guestCompany: "",
      xUrl: "https://x.com/i/broadcasts/1yKAPMvzBjaxb",
    },
    {
      title: "Episode 6",
      episodeTitle: "You Need Money to Receive Money. That's the Whole Problem.",
      guest: "Tochi Chukwuemeka",
      guestTitle: "Co-Founder",
      guestCompany: "PajCash",
      xUrl: "https://x.com/thespeakerlisan/status/2045494019497836568",
    },
    {
      title: "Episode 5",
      episodeTitle: "Canada Is Exporting Its Dollar Abroad and He's Building the Fix",
      guest: "Kevin Zhang",
      guestTitle: "Co-Founder",
      guestCompany: "Loon",
      xUrl: "https://x.com/thespeakerlisan/status/2045140831976542240",
      youtubeUrl: "https://www.youtube.com/watch?v=7JWEhgWm4M4",
    },
    {
      title: "Episode 4",
      episodeTitle: "He Flew to Bangalore for a Bitcoin Meetup and Built India's Biggest Exchange",
      guest: "Sunny Ray",
      guestTitle: "Co-Founder, RaaSRocket & President",
      guestCompany: "Unocoin",
      xUrl: "https://x.com/thespeakerlisan/status/2044877463785013252",
      youtubeUrl: "https://www.youtube.com/watch?v=EreH4lVMzUA",
    },
    {
      title: "Episode 3",
      episodeTitle: "16 Years Watching Investors Walk In. Then He Became One.",
      guest: "Varun Turlapati",
      guestTitle: "Managing Director",
      guestCompany: "Chaanakya Capital",
      xUrl: "https://x.com/thespeakerlisan/status/2040173652868767985",
      youtubeUrl: "https://www.youtube.com/watch?v=oPjqOAxsND0",
    },
    {
      title: "Episode 2",
      episodeTitle: "She Built a Factory at 19 with Just a Bank Loan and a Network She Earned",
      guest: "Yangchen Sharma",
      guestTitle: "General Partner",
      guestCompany: "Roundtable Ventures",
      xUrl: "https://x.com/thespeakerlisan/status/2039471823423975808",
      youtubeUrl: "https://www.youtube.com/watch?v=v9g4T7kPw48",
    },
    {
      title: "Episode 1",
      episodeTitle: "From Operating Companies to Growing Families, Creating Systems Is Key",
      guest: "Charles Cormier",
      guestTitle: "CEO",
      guestCompany: "RaaSRocket",
      xUrl: "https://x.com/thespeakerlisan/status/2038694757166379327",
      youtubeUrl: "https://www.youtube.com/watch?v=1RGwcT57MJU",
    },
  ],

  blurb:
    "The Superlative Podcast is a 20-30 minute live conversation hosted by Edward Buchi, co-founder of Sacred Protocol. Each episode features one guest from startups, media, sports, or finance\u2014a founder, investor, or operator with a real story and a point of view worth putting on record. No edits, no post-production. Streamed live to X and YouTube.",

  verticals: [
    { title: "Startups", description: "Founders and builders shipping products" },
    { title: "Media", description: "Executives and creators shaping culture" },
    { title: "Sports", description: "Athletes and operators behind the game" },
    { title: "Finance", description: "Investors and dealmakers moving capital" },
  ],
};
